export const caseNames: { [key: string]: Array<string> } = {
  "1c/1c": ["1c/1c"],
  "3c/3c": ["3c/3c"],
  "good tent/tent": ["right tent/right tent", "left tent/left tent"],
  "bad tent/tent": ["right tent/left tent", "left tent/right tent"],
  "good tent/whale": [
    "right tent/left whale",
    "left tent/right whale",
    "right whale/left tent",
    "left whale/right tent",
  ],
  "bad tent/whale": [
    "right tent/right whale",
    "left tent/left whale",
    "right whale/right tent",
    "left whale/left tent",
  ],
  "good whale/whale": ["right whale/right whale", "left whale/left whale"],
  "bad whale/whale": ["right whale/left whale", "left whale/right whale"],
  "gem/gem": ["gem/gem"],
  "gem/squid": ["squid/gem", "gem/squid"],
  "gem/axe": ["gem/right axe", "gem/left axe", "right axe/gem", "left axe/gem"],
  "gem/spill": [
    "gem/right spill",
    "gem/left spill",
    "right spill/gem",
    "left spill/gem",
  ],
  "good spill/axe": [
    "right spill/right axe",
    "right axe/right spill",
    "left spill/left axe",
    "left axe/left spill",
  ],
  "bad spill/axe": [
    "right spill/left axe",
    "right axe/left spill",
    "left spill/right axe",
    "left axe/right spill",
  ],
  "same spill/spill": ["left spill/left spill", "right spill/right spill"],
  "opp spill/spill": ["left spill/right spill", "right spill/left spill"],
  "same axe/axe": ["left axe/left axe", "right axe/right axe"],
  "opp axe/axe": ["left axe/right axe", "right axe/left axe"],
  "squid/squid": ["squid/squid"],
  "squid/axe": [
    "squid/right axe",
    "squid/left axe",
    "right axe/squid",
    "left axe/squid",
  ],
  "squid/spill": [
    "squid/right spill",
    "squid/left spill",
    "right spill/squid",
    "left spill/squid",
  ],
  "good bunny/bunny": ["right bunny/right bunny", "left bunny/left bunny"],
  "bad bunny/bunny": ["right bunny/left bunny", "left bunny/right bunny"],
  "good bunny/thumb": [
    "right bunny/right thumb",
    "left bunny/left thumb",
    "right thumb/right bunny",
    "left thumb/left bunny",
  ],
  "bad bunny/thumb": [
    "right bunny/left thumb",
    "left bunny/right thumb",
    "right thumb/left bunny",
    "left thumb/right bunny",
  ],
  "good thumb/thumb": ["right thumb/right thumb", "left thumb/left thumb"],
  "bad thumb/thumb": ["right thumb/left thumb", "left thumb/right thumb"],
  "cadj/copp": ["cadj/copp", "copp/cadj"],
  "good bird/scottie": [
    "left bird/right scottie",
    "left scottie/right bird",
    "right bird/left scottie",
    "right scottie/left bird",
  ],
  "bad bird/scottie": [
    "left bird/left scottie",
    "left scottie/left bird",
    "right bird/right scottie",
    "right scottie/right bird",
  ],
  "hazard/scottie": [
    "hazard/right scottie",
    "hazard/left scottie",
    "left scottie/hazard",
    "right scottie/hazard",
  ],
  "shell/scottie": [
    "shell/right scottie",
    "shell/left scottie",
    "left scottie/shell",
    "right scottie/shell",
  ],
  "kite/tie": [
    "left kite/tie",
    "right kite/tie",
    "tie/right kite",
    "tie/left kite",
    "left kite/tie2",
    "right kite/tie2",
    "tie2/right kite",
    "tie2/left kite",
  ],
  "good kite/pinwheel": [
    "left kite/left pinwheel",
    "right kite/right pinwheel",
    "right pinwheel/right kite",
    "left pinwheel/left kite",
  ],
  "bad kite/pinwheel": [
    "left kite/right pinwheel",
    "right kite/left pinwheel",
    "right pinwheel/left kite",
    "left pinwheel/right kite",
  ],
  "tree/pinwheel": [
    "tree/right pinwheel",
    "tree/left pinwheel",
    "right pinwheel/tree",
    "left pinwheel/tree",
    "tree2/right pinwheel",
    "tree2/left pinwheel",
    "right pinwheel/tree2",
    "left pinwheel/tree2",
  ],
  "good tree/tie": ["tree2/tie", "tie/tree2", "tie2/tree", "tree/tie2"],
  "bad tree/tie": ["tree/tie", "tie/tree", "tie2/tree2", "tree2/tie2"],
  "cut/tie": [
    "left cut/tie",
    "right cut/tie",
    "tie/left cut",
    "tie/right cut",
    "left cut/tie2",
    "right cut/tie2",
    "tie2/left cut",
    "tie2/right cut",
  ],
  "good cut/pinwheel": [
    "left cut/left pinwheel",
    "right cut/right pinwheel",
    "left pinwheel/left cut",
    "right pinwheel/right cut",
  ],
  "bad cut/pinwheel": [
    "left cut/right pinwheel",
    "right cut/left pinwheel",
    "left pinwheel/right cut",
    "right pinwheel/left cut",
  ],
};
