export const categories: { [key: string]: any } = {
  "3c": {
    "0e": ["1c/1c", "3c/3c"],
    "1e": [
      "good tent/tent",
      "bad tent/tent",
      "good tent/whale",
      "bad tent/whale",
      "good whale/whale",
      "bad whale/whale",
    ],
    "2e": [
      "gem/gem",
      "gem/squid",
      "gem/axe",
      "gem/knight",
      "good knight/axe",
      "bad knight/axe",
      "same knight/knight",
      "opp knight/knight",
      "same axe/axe",
      "opp axe/axe",
      "squid/squid",
      "squid/axe",
      "squid/knight",
    ],
    "3e": [
      "good bunny/bunny",
      "bad bunny/bunny",
      "good bunny/thumb",
      "bad bunny/thumb",
      "good thumb/thumb",
      "bad thumb/thumb",
    ],
  },
  "bar/diag": {
    "0e": ["cadj/copp"],
    "1e": ["good bird/yoshi", "bad bird/yoshi", "hazard/yoshi", "shell/yoshi"],
    "2e": [
      "kite/tie",
      "good kite/pinwheel",
      "bad kite/pinwheel",
      "tree/pinwheel",
      "good tree/tie",
      "bad tree/tie",
      "cut/tie",
      "good cut/pinwheel",
      "bad cut/pinwheel",
    ],
  },
  "bar/bar": {
    "0e": ["cadj/cadj"],
    "1e": [
      "shell/shell",
      "shell/bird",
      "shell/hazard",
      "good bird/bird",
      "bad bird/bird",
      "bird/hazard",
      "hazard/hazard",
    ],
    "2e": [
      "good kite/cut",
      "bad kite/cut",
      "good t/t",
      "bad t/t",
      "good cut/cut",
      "bad cut/cut",
      "kite/t",
      "cut/t",
      "good kite/kite",
      "bad kite/kite",
    ],
  },
  "diag/diag": {
    "0e": ["copp/copp"],
    "1e": ["yoshi/yoshi"],
    "2e": ["good tie/tie", "bad tie/tie", "tie/n", "good n/n", "bad n/n"],
  },
  "4c": {},
};
